/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClaseVentanas;

import claseprin.dbConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.*;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Slad
 */
public class VParqueo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VParqueo.class.getName());

    /**
     * Creates new form VParqueo
     */
    public VParqueo() {
        initComponents();
        generarMapaPorArea();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public void generarMapaPorArea() {

    panelMapaGeneral.removeAll(); // limpiar mapa

    try (Connection con = dbConnection.conectar()) {

        // 1. Obtener todas las áreas ordenadas
        PreparedStatement psAreas = con.prepareStatement(
            "SELECT area_id, nombre, tipo_vehiculo FROM area ORDER BY area_id ASC"
        );

        ResultSet rsAreas = psAreas.executeQuery();

        panelMapaGeneral.setLayout(new BoxLayout(panelMapaGeneral, BoxLayout.Y_AXIS));

        while (rsAreas.next()) {

            String areaID = rsAreas.getString("area_id");
            String nombre = rsAreas.getString("nombre");
            String tipo = rsAreas.getString("tipo_vehiculo");

            // Crear panel de área
            JPanel panelArea = new JPanel();
            panelArea.setBorder(javax.swing.BorderFactory.createTitledBorder(
                    nombre + " (" + areaID + ")"));
            panelArea.setLayout(new java.awt.GridLayout(0, 12, 8, 8));  

            // 2. obtener SPOTS
            PreparedStatement psSpots = con.prepareStatement(
                "SELECT spot_id, tipo_vehiculo, status FROM spots WHERE area_id=? ORDER BY spot_id ASC"
            );
            psSpots.setString(1, areaID);
            ResultSet rsSpots = psSpots.executeQuery();

            while (rsSpots.next()) {

                String spotID = rsSpots.getString("spot_id");
                String tipoVeh = rsSpots.getString("tipo_vehiculo");
                String status = rsSpots.getString("status");

                // CREAR LABEL SIN ÍCONO
                JLabel lbl = new JLabel(spotID);
                 lbl.setOpaque(true);
                 lbl.setPreferredSize(new Dimension(60, 60));
                 lbl.setHorizontalAlignment(JLabel.CENTER);
                 lbl.setVerticalAlignment(JLabel.CENTER);
                 lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

                lbl.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK, 2));


                // COLOR
                if (status.equalsIgnoreCase("FREE")) {
                lbl.setBackground(new Color(0, 200, 0)); // Verde
               }else if (status.equalsIgnoreCase("OCCUPIED")) {
                lbl.setBackground(new Color(200, 0, 0)); // Rojo
               }else if (status.equalsIgnoreCase("TEMPORAL")) {
               lbl.setBackground(new Color(255, 215, 0)); // Amarillo dorado
               }


                // Tooltip con información
                lbl.setToolTipText(
                    "<html>"
                    + "<b>Spot:</b> " + spotID + "<br>"
                    + "<b>Área:</b> " + areaID + "<br>"
                    + "<b>Vehículo:</b> " + tipoVeh + "<br>"
                    + "<b>Estado:</b> " + status
                    + "</html>"
                );

                panelArea.add(lbl);
            }

            panelMapaGeneral.add(panelArea);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    panelMapaGeneral.revalidate();
    panelMapaGeneral.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapaGeneral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMapaGeneral.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout panelMapaGeneralLayout = new javax.swing.GroupLayout(panelMapaGeneral);
        panelMapaGeneral.setLayout(panelMapaGeneralLayout);
        panelMapaGeneralLayout.setHorizontalGroup(
            panelMapaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        panelMapaGeneralLayout.setVerticalGroup(
            panelMapaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMapaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMapaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VParqueo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelMapaGeneral;
    // End of variables declaration//GEN-END:variables
}
